---
name: CI/CD
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  docker-build-and-push:
    uses: dceoy/gh-actions-for-devops/.github/workflows/docker-build-and-push.yml@main
    permissions:
      contents: write
      packages: write
    with:
      registry: docker.io
      registry-user: ${{ github.actor }}
      image-name: ${{ github.actor }}/apt-file
      platforms: linux/amd64,linux/arm64
      context: .
      file: ./Dockerfile
      push: true
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
